// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7bmzsXKoqiibYO0ztAKHeeZ_RZpzqJxQ',
    appId: '1:334210246979:web:380e4cf7051195052ce7f6',
    messagingSenderId: '334210246979',
    projectId: 'nitrooperacional-40c1e',
    authDomain: 'nitrooperacional-40c1e.firebaseapp.com',
    storageBucket: 'nitrooperacional-40c1e.firebasestorage.app',
    measurementId: 'G-4KKSJKKEV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq1u_UK1m8Or7WewoQ4KSnZVx8y6-O_S8',
    appId: '1:334210246979:android:3a473d86bac22d0a2ce7f6',
    messagingSenderId: '334210246979',
    projectId: 'nitrooperacional-40c1e',
    storageBucket: 'nitrooperacional-40c1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6orre2-Xenc4hFWG2JHyY-qsg2fbLlM0',
    appId: '1:334210246979:ios:86431db419cc24c12ce7f6',
    messagingSenderId: '334210246979',
    projectId: 'nitrooperacional-40c1e',
    storageBucket: 'nitrooperacional-40c1e.firebasestorage.app',
    iosClientId: '334210246979-kmmoo0mmpb3medt8utckcp7n82jhjp03.apps.googleusercontent.com',
    iosBundleId: 'com.example.nitroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6orre2-Xenc4hFWG2JHyY-qsg2fbLlM0',
    appId: '1:334210246979:ios:86431db419cc24c12ce7f6',
    messagingSenderId: '334210246979',
    projectId: 'nitrooperacional-40c1e',
    storageBucket: 'nitrooperacional-40c1e.firebasestorage.app',
    iosClientId: '334210246979-kmmoo0mmpb3medt8utckcp7n82jhjp03.apps.googleusercontent.com',
    iosBundleId: 'com.example.nitroApp',
  );
}
